# Generated by Django 4.1.1 on 2022-09-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query_ID', models.IntegerField()),
                ('Full_Query', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_ID', models.IntegerField()),
                ('Summary_Work', models.CharField(max_length=100)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.query')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSD_CPU', models.FloatField()),
                ('SE_CPU', models.FloatField()),
                ('DBC_CPU', models.FloatField()),
                ('CSD_Memory', models.FloatField()),
                ('SE_Memory', models.FloatField()),
                ('DBC_Memory', models.FloatField()),
                ('CSD_Power', models.FloatField()),
                ('SE_Power', models.FloatField()),
                ('DBC_Power', models.FloatField()),
                ('CSD_Network', models.FloatField()),
                ('SE_Network', models.FloatField()),
                ('DBC_Network', models.FloatField()),
                ('CSD_IO', models.FloatField()),
                ('SE_IO', models.FloatField()),
                ('DBC_IO', models.FloatField()),
                ('CSD_Time', models.FloatField()),
                ('SE_Time', models.FloatField()),
                ('DBC_Time', models.FloatField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.work')),
            ],
        ),
    ]
