# Generated by Django 4.1.1 on 2022-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=156, verbose_name='specific_id')),
                ('horizon_width', models.CharField(max_length=100, verbose_name='horizon_width')),
                ('vertical_width', models.CharField(max_length=100, verbose_name='vertical_width')),
                ('x_location', models.CharField(max_length=100, verbose_name='x_location')),
                ('y_location', models.CharField(max_length=100, verbose_name='y_location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
