# Generated by Django 4.1.1 on 2022-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_data_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='KospiPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, unique=True, verbose_name='날짜')),
                ('close', models.FloatField(null=True, verbose_name='종가')),
                ('open', models.FloatField(null=True, verbose_name='시가')),
            ],
        ),
    ]
