# Generated by Django 4.1.1 on 2022-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPC_H_QUERY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.IntegerField(verbose_name='queryid')),
                ('work_id', models.IntegerField(verbose_name='workid')),
                ('full_query', models.CharField(max_length=600, verbose_name='full_query')),
                ('summary_work', models.CharField(max_length=200, verbose_name='summary_work')),
            ],
        ),
    ]
